# 🐍 Python Data Structures — Practice Worksheet
### 18 Tasks covering Numbers, Booleans, Strings, Loops, Lists, Tuples, Dictionaries, Sets, NumPy & Pandas

---

> 📌 **Instructions**
> - Complete **all 18 tasks** from top to bottom — each builds on previous concepts.
> - Fill in every `# YOUR CODE HERE` block. Do **not** change task descriptions.
> - Run each cell after completing it to verify your output.
> - Expected outputs are shown where helpful.

---


## ⚙️ Setup — Run This Cell First


In [1]:
import random
import collections
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
print("All libraries imported successfully ✅")


All libraries imported successfully ✅


---
# 🔢 Section 1 — Primitive Data Types


## 📝 Task 1 — Numbers & Arithmetic

### Background
Python supports two main numeric types: `int` (whole numbers) and `float` (decimals). You can use the standard arithmetic operators: `+`, `-`, `*`, `/`, `//` (floor division), `%` (modulo), `**` (exponentiation).

### 🎯 Your Task
Given `a = 17` and `b = 5`, compute and **print** each of the following with a descriptive label:

| Expression | Expected Output |
|---|---|
| `a + b` | 22 |
| `a - b` | 12 |
| `a * b` | 85 |
| `a / b` | 3.4 |
| `a // b` | 3 |
| `a % b` | 2 |
| `a ** b` | 1419857 |

Then print the **type** of `a` and the **type** of `a / b` and explain (in a comment) why they differ.

> 💡 **Hint:** Use `print(f"a + b = {a + b}")` for clean labelled output. Use `type()` to check types.


In [20]:
a = 17
b = 5

print(f"a + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b = {a * b}")
print(f"a / b = {a / b}")
print(f"a // b = {a // b}")
print(f"a % b = {a % b}")
print(f"a ** b = {a ** b}")
print(f"type of a = {type(a)}")
print(f"type of a / b = {type(a / b)}")
# Comment: a is an int, while a / b uses true division and returns a float.
# Answer: int vs float


a + b = 22
a - b = 12
a * b = 85
a / b = 3.4
a // b = 3
a % b = 2
a ** b = 1419857
type of a = <class 'int'>
type of a / b = <class 'float'>


## 📝 Task 2 — Boolean Logic

### Background
Python's Boolean type has two values: `True` and `False`. Logical operators are written as English words: `and`, `or`, `not`. The XOR (exclusive or) result can be checked with `!=`.

### 🎯 Your Task
Given `p = True` and `q = False`:

1. Print the result of `p and q`, `p or q`, `not p`, and `p != q`
2. Create a variable `score = 73` and write an `if / elif / else` block that prints:
   - `"Distinction"` if score ≥ 85
   - `"Merit"` if score is between 70 and 84 (inclusive)
   - `"Pass"` if score is between 50 and 69 (inclusive)
   - `"Fail"` otherwise

> 💡 **Hint:** Use `elif` for multiple conditions. The order matters — check the highest threshold first.


In [21]:
p = True
q = False

print(f"p and q = {p and q}")
print(f"p or q = {p or q}")
print(f"not p = {not p}")
print(f"p != q = {p != q}")
score = 73
if score >= 85:
    print("Distinction")
elif score >= 70:
    print("Merit")
elif score >= 50:
    print("Pass")
else:
    print("Fail")


p and q = False
p or q = True
not p = False
p != q = True
Merit


## 📝 Task 3 — String Operations

### Background
Strings in Python are sequences of characters. Useful built-in string methods include `.upper()`, `.lower()`, `.replace()`, `.split()`, `.strip()`, and `.count()`. You can also use `len()`, slicing `[start:end]`, and f-strings for formatting.

### 🎯 Your Task
Work with the sentence below and complete all five operations:

```python
sentence = "  Python is a powerful programming language  "
```

| # | Operation | Expected Result |
|---|-----------|-----------------|
| 1 | Strip whitespace | `"Python is a powerful programming language"` |
| 2 | Convert to UPPERCASE | `"PYTHON IS A POWERFUL PROGRAMMING LANGUAGE"` |
| 3 | Count the word `"a"` (exact, case-sensitive) | `1` |
| 4 | Replace `"powerful"` with `"versatile"` | `"Python is a versatile programming language"` |
| 5 | Split into a list of words | `['Python', 'is', 'a', 'versatile', ...]` |

Finally, use an **f-string** to print: `"The sentence has X words."` (where X is the actual count).

> 💡 **Hint:** Chain methods: `sentence.strip().upper()`. Use `.split()` with no arguments to split on any whitespace.


In [22]:
sentence = "  Python is a powerful programming language  "

clean = sentence.strip()
print(clean)
print(clean.upper())
count_a = clean.split().count("a")
print(f'Count of "a" = {count_a}')
new_sentence = clean.replace("powerful", "versatile")
print(new_sentence)
words = new_sentence.split()
print(words)
print(f"The sentence has {len(words)} words.")


Python is a powerful programming language
PYTHON IS A POWERFUL PROGRAMMING LANGUAGE
Count of "a" = 1
Python is a versatile programming language
['Python', 'is', 'a', 'versatile', 'programming', 'language']
The sentence has 6 words.


## 📝 Task 4 — Loops & Conditionals

### Background
`for` loops iterate over a sequence. `while` loops run as long as a condition is `True`. Use `break` to exit early and `continue` to skip to the next iteration.

### 🎯 Your Task

**Part A:** Use a `for` loop with `range()` to print all **even numbers from 1 to 30** on a single line separated by spaces.

**Part B:** Use a `while` loop to compute the **sum of all odd numbers from 1 to 99** (i.e., 1 + 3 + 5 + … + 99). Print the result.
> Expected answer: 2500

**Part C:** Use a `for` loop over `range(1, 21)`. Print the number normally, **but**:
- If divisible by both 3 and 5 → print `"FizzBuzz"`
- If divisible by 3 only → print `"Fizz"`
- If divisible by 5 only → print `"Buzz"`

> 💡 **Hint for Part A:** Use `print(n, end=' ')` to stay on the same line, or build a list and use `' '.join(...)`.  
> 💡 **Hint for Part C:** Check the combined condition (`% 3 == 0 and % 5 == 0`) **first** before the individual ones.


In [23]:
# Part A: Even numbers from 1 to 30
evens = [n for n in range(1, 31) if n % 2 == 0]
print("Even numbers:", " ".join(str(n) for n in evens))

# Part B: Sum of odd numbers from 1 to 99
odd_sum = 0
n = 1
while n <= 99:
    odd_sum += n
    n += 2
print("Sum of odd numbers 1 to 99:", odd_sum)

# Part C: FizzBuzz from 1 to 20
for n in range(1, 21):
    if n % 3 == 0 and n % 5 == 0:
        print("FizzBuzz")
    elif n % 3 == 0:
        print("Fizz")
    elif n % 5 == 0:
        print("Buzz")
    else:
        print(n)


Even numbers: 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30
Sum of odd numbers 1 to 99: 2500
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz


---
# 📋 Section 2 — Lists


## 📝 Task 5 — List Basics: Create, Access, Modify

### Background
A Python list is **mutable** and **ordered**. Elements are accessed by zero-based index. Negative indices count from the end (`-1` is the last element). Common methods: `.append()`, `.insert()`, `.remove()`, `.pop()`, `.sort()`, `.reverse()`.

### 🎯 Your Task
Start with:
```python
fruits = ["mango", "banana", "apple", "cherry", "orange"]
```

Perform the following operations **in order**, printing the list after each step:

1. Print the **first** and **last** element using positive and negative indexing.
2. **Append** `"grape"` to the end.
3. **Insert** `"kiwi"` at index 2.
4. **Remove** `"banana"` from the list.
5. **Pop** the element at index 0 and print what was removed.
6. **Sort** the list alphabetically and print it.
7. **Reverse** the sorted list and print it.

> 💡 **Hint:** Remember that `.pop(index)` returns the removed element, so you can capture it: `removed = fruits.pop(0)`.


In [24]:
fruits = ["mango", "banana", "apple", "cherry", "orange"]
print("Original:", fruits)
print("First element:", fruits[0])
print("Last element:", fruits[-1])
fruits.append("grape")
print("After append:", fruits)
fruits.insert(2, "kiwi")
print("After insert:", fruits)
fruits.remove("banana")
print("After remove banana:", fruits)
removed = fruits.pop(0)
print("Removed element:", removed)
print("After pop:", fruits)
fruits.sort()
print("Sorted:", fruits)
fruits.reverse()
print("Reversed:", fruits)


Original: ['mango', 'banana', 'apple', 'cherry', 'orange']
First element: mango
Last element: orange
After append: ['mango', 'banana', 'apple', 'cherry', 'orange', 'grape']
After insert: ['mango', 'banana', 'kiwi', 'apple', 'cherry', 'orange', 'grape']
After remove banana: ['mango', 'kiwi', 'apple', 'cherry', 'orange', 'grape']
Removed element: mango
After pop: ['kiwi', 'apple', 'cherry', 'orange', 'grape']
Sorted: ['apple', 'cherry', 'grape', 'kiwi', 'orange']
Reversed: ['orange', 'kiwi', 'grape', 'cherry', 'apple']


## 📝 Task 6 — List Slicing

### Background
Slicing extracts a **sub-list** using the syntax `list[start:stop:step]`:
- `start` is inclusive, `stop` is exclusive
- A negative `step` reverses the direction
- Omitting `start` or `stop` defaults to the beginning or end

### 🎯 Your Task
Work with:
```python
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

| # | Slice | Expected Result |
|---|-------|-----------------|
| 1 | First 4 elements | `[0, 1, 2, 3]` |
| 2 | Last 3 elements | `[7, 8, 9]` |
| 3 | Elements from index 2 to 7 | `[2, 3, 4, 5, 6]` |
| 4 | Every second element | `[0, 2, 4, 6, 8]` |
| 5 | The entire list **reversed** | `[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]` |
| 6 | Last 5 elements **reversed** | `[9, 8, 7, 6, 5]` |

> 💡 **Hint:** To reverse use `[::-1]`. For last N items use `[-N:]`. To reverse a slice: `numbers[4:9][::-1]` reverses a sub-section.


In [25]:
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print("First 4:", numbers[:4])
print("Last 3:", numbers[-3:])
print("Index 2 to 7:", numbers[2:7])
print("Every second element:", numbers[::2])
print("Reversed:", numbers[::-1])
print("Last 5 reversed:", numbers[-5:][::-1])


First 4: [0, 1, 2, 3]
Last 3: [7, 8, 9]
Index 2 to 7: [2, 3, 4, 5, 6]
Every second element: [0, 2, 4, 6, 8]
Reversed: [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
Last 5 reversed: [9, 8, 7, 6, 5]


## 📝 Task 7 — List Comprehensions

### Background
List comprehensions are a concise way to create lists:
```python
[expression for item in iterable if condition]
```
They replace many `for` loops with a single readable line.

### 🎯 Your Task
Use **list comprehensions** (no regular for-loops!) to create and print each of the following:

1. A list of the **squares** of numbers 1 through 15: `[1, 4, 9, 16, ...]`
2. A list of numbers from 1–50 that are **divisible by 3 or 5** (but not both): `[3, 5, 6, 9, 10, ...]`
3. A list of the **lengths** of each word in the sentence `"the quick brown fox jumps over the lazy dog"`
4. A list of **uppercase versions** of only the words that have **5 or more letters**: `['QUICK', 'BROWN', 'JUMPS', 'LAZY']` *(hint: 'over' has 4, skip it)*

> 💡 **Hint for #2:** `(n % 3 == 0) != (n % 5 == 0)` is Python's way to express XOR for two conditions.  
> 💡 **Hint for #3:** `sentence.split()` gives you the word list.


In [26]:
# 1. Squares of 1 to 15
squares = [n**2 for n in range(1, 16)]
print("Squares:", squares)

# 2. Numbers 1-50 divisible by 3 OR 5 but NOT both
div3or5 = [n for n in range(1, 51) if (n % 3 == 0) != (n % 5 == 0)]
print("Divisible by 3 or 5 but not both:", div3or5)

# 3. Lengths of each word in the sentence
word_lengths = [len(word) for word in sentence.split()]
print("Word lengths:", word_lengths)

# 4. Uppercase words with 5 or more letters
long_upper = [word.upper() for word in sentence.split() if len(word) >= 5]
print("Uppercase long words:", long_upper)


Squares: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225]
Divisible by 3 or 5 but not both: [3, 5, 6, 9, 10, 12, 18, 20, 21, 24, 25, 27, 33, 35, 36, 39, 40, 42, 48, 50]
Word lengths: [6, 2, 1, 8, 11, 8]
Uppercase long words: ['PYTHON', 'POWERFUL', 'PROGRAMMING', 'LANGUAGE']


## 📝 Task 8 — Nested Lists & the `collections.Counter`

### Background
A **list of lists** creates a 2D (matrix-like) structure. Access elements with `matrix[row][col]`.  
`collections.Counter` is a dictionary subclass that counts how many times each element appears in an iterable.

### 🎯 Your Task

**Part A — Nested List:**  
Create the following 3×3 matrix as a list of lists and then:
```
matrix = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]
```
- Print the **second row** (index 1)
- Print the **element at row 2, column 1** (value: 8)
- Use a nested list comprehension to create a **transposed** version (rows become columns)
  - Expected: `[[1, 4, 7], [2, 5, 8], [3, 6, 9]]`

**Part B — Counter:**  
Generate a list of 300 random integers between 1 and 10 (inclusive), then:
- Use `collections.Counter` to count each number
- Print the **3 most common** numbers and their counts
- Print the **least common** number

> 💡 **Hint for transpose:** `[[matrix[r][c] for r in range(3)] for c in range(3)]`  
> 💡 **Hint for Counter:** `counter.most_common(3)` returns the top 3 as a list of `(value, count)` tuples.


In [27]:
import collections, random

matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]
print("Second row:", matrix[1])
print("Element at row 2, col 1:", matrix[2][1])
transpose = [[matrix[r][c] for r in range(3)] for c in range(3)]
print("Transposed:", transpose)

random.seed(42)
rand_numbers = [random.randint(1, 10) for _ in range(300)]
counter = collections.Counter(rand_numbers)
print("Top 3 most common:", counter.most_common(3))
least_common = min(counter.items(), key=lambda x: x[1])
print("Least common:", least_common)


Second row: [4, 5, 6]
Element at row 2, col 1: 8
Transposed: [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
Top 3 most common: [(4, 42), (2, 40), (9, 35)]
Least common: (6, 22)


---
# 🔒 Section 3 — Tuples


## 📝 Task 9 — Tuples: Immutability & Practical Uses

### Background
Tuples look like lists but use `()` instead of `[]`. They are **immutable** — you cannot add, remove, or change elements after creation. This makes them useful for fixed data like coordinates, RGB colours, or records. Tuples support indexing, slicing, and iteration just like lists.

### 🎯 Your Task

**Part A — Basic Tuple Operations:**
```python
student = ("Alice", 22, "Computer Science", 3.8)
```
- Print the student's name (index 0) and GPA (index 3)
- Try to change the name to `"Bob"` — catch the resulting `TypeError` with a `try/except` block and print `"Tuples are immutable!"`
- Unpack the tuple into 4 separate variables: `name, age, major, gpa` and print each

**Part B — List of Tuples:**  
You have coordinates of 5 cities:
```python
cities = [("Karachi", 24.86, 67.01),
          ("Lahore",  31.55, 74.35),
          ("Islamabad", 33.72, 73.06),
          ("Peshawar", 34.01, 71.57),
          ("Quetta",  30.18, 66.99)]
```
- Loop over the list and print each city in the format: `"City: Karachi | Lat: 24.86 | Lon: 67.01"`
- Sort the cities by **latitude** (ascending) and print the sorted list

> 💡 **Hint for sorting:** `sorted(cities, key=lambda c: c[1])` sorts by the second element of each tuple.


In [28]:
# Part A
student = ("Alice", 22, "Computer Science", 3.8)

print("Name:", student[0])
print("GPA:", student[3])
try:
    student[0] = "Bob"
except TypeError:
    print("Tuples are immutable!")
name, age, major, gpa = student
print(name)
print(age)
print(major)
print(gpa)

# Part B
cities = [("Karachi",   24.86, 67.01),
          ("Lahore",    31.55, 74.35),
          ("Islamabad", 33.72, 73.06),
          ("Peshawar",  34.01, 71.57),
          ("Quetta",    30.18, 66.99)]
for city, lat, lon in cities:
    print(f"City: {city} | Lat: {lat} | Lon: {lon}")
sorted_by_lat = sorted(cities, key=lambda c: c[1])
print("Sorted by latitude:", sorted_by_lat)


Name: Alice
GPA: 3.8
Tuples are immutable!
Alice
22
Computer Science
3.8
City: Karachi | Lat: 24.86 | Lon: 67.01
City: Lahore | Lat: 31.55 | Lon: 74.35
City: Islamabad | Lat: 33.72 | Lon: 73.06
City: Peshawar | Lat: 34.01 | Lon: 71.57
City: Quetta | Lat: 30.18 | Lon: 66.99
Sorted by latitude: [('Karachi', 24.86, 67.01), ('Quetta', 30.18, 66.99), ('Lahore', 31.55, 74.35), ('Islamabad', 33.72, 73.06), ('Peshawar', 34.01, 71.57)]


---
# 📖 Section 4 — Dictionaries


## 📝 Task 10 — Dictionary Basics: Create, Access, Update

### Background
A dictionary stores data as **key → value** pairs. Keys must be unique and immutable (strings, numbers, tuples). Values can be anything. Key methods: `.keys()`, `.values()`, `.items()`, `.get()`, `.update()`, `.pop()`.

### 🎯 Your Task
Start with this student record:
```python
student = {
    "name": "Sara",
    "age": 20,
    "courses": ["Math", "Physics", "CS"],
    "grades": {"Math": 88, "Physics": 75, "CS": 92}
}
```

1. Print Sara's **name** and **age**
2. Print her **list of courses**
3. Print her **CS grade** (access the nested dictionary)
4. Add a new key `"year"` with value `2`
5. Update her **age** to `21`
6. Remove the `"Physics"` grade from the nested `"grades"` dictionary using `.pop()`
7. Loop over all key-value pairs with `.items()` and print them line by line
8. Print a list of all **keys** and a list of all **values**

> 💡 **Hint:** Access nested dicts with chained brackets: `student["grades"]["CS"]`  
> 💡 **Hint:** `student.get("email", "Not found")` returns a default value if the key doesn't exist.


In [29]:
student = {
    "name": "Sara",
    "age": 20,
    "courses": ["Math", "Physics", "CS"],
    "grades": {"Math": 88, "Physics": 75, "CS": 92}
}

print("Name:", student["name"])
print("Age:", student["age"])
print("Courses:", student["courses"])
print("CS grade:", student["grades"]["CS"])
student["year"] = 2
student["age"] = 21
student["grades"].pop("Physics", None)
for key, value in student.items():
    print(f"{key}: {value}")
print("Keys:", list(student.keys()))
print("Values:", list(student.values()))


Name: Sara
Age: 20
Courses: ['Math', 'Physics', 'CS']
CS grade: 92
name: Sara
age: 21
courses: ['Math', 'Physics', 'CS']
grades: {'Math': 88, 'CS': 92}
year: 2
Keys: ['name', 'age', 'courses', 'grades', 'year']
Values: ['Sara', 21, ['Math', 'Physics', 'CS'], {'Math': 88, 'CS': 92}, 2]


## 📝 Task 11 — Dictionary Comprehension & Word Frequency Counter

### Background
Just like list comprehensions, you can build dictionaries in one line:
```python
{key_expr: value_expr for item in iterable if condition}
```
Dictionaries are perfect for counting frequencies — a pattern you'll use constantly in data science.

### 🎯 Your Task

**Part A — Dictionary Comprehension:**
1. Create a dictionary mapping each number 1–10 to its **cube**: `{1: 1, 2: 8, 3: 27, ...}`
2. Create a dictionary mapping each number 1–20 to `"even"` or `"odd"`: `{1: 'odd', 2: 'even', ...}`

**Part B — Word Frequency Counter:**  
Count how many times each word appears in the text below, ignoring case. Print the result sorted by **frequency (descending)**.

```python
text = "to be or not to be that is the question to be is to think"
```
Expected top entries: `to: 4, be: 3, is: 2, ...`

> 💡 **Hint for Part B:** Start with `freq = {}`, then loop over `text.lower().split()`.  
> Use `freq[word] = freq.get(word, 0) + 1` to safely increment counts.  
> Sort with `sorted(freq.items(), key=lambda x: x[1], reverse=True)`.


In [30]:
# Part A — Dictionary comprehensions
cubes = {n: n**3 for n in range(1, 11)}
print("Cubes:", cubes)
even_odd = {n: ("even" if n % 2 == 0 else "odd") for n in range(1, 21)}
print("Even/Odd mapping:", even_odd)

text = "to be or not to be that is the question to be is to think"
freq = {}
for word in text.lower().split():
    freq[word] = freq.get(word, 0) + 1
sorted_freq = sorted(freq.items(), key=lambda x: x[1], reverse=True)
print("Word frequencies:", sorted_freq)


Cubes: {1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000}
Even/Odd mapping: {1: 'odd', 2: 'even', 3: 'odd', 4: 'even', 5: 'odd', 6: 'even', 7: 'odd', 8: 'even', 9: 'odd', 10: 'even', 11: 'odd', 12: 'even', 13: 'odd', 14: 'even', 15: 'odd', 16: 'even', 17: 'odd', 18: 'even', 19: 'odd', 20: 'even'}
Word frequencies: [('to', 4), ('be', 3), ('is', 2), ('or', 1), ('not', 1), ('that', 1), ('the', 1), ('question', 1), ('think', 1)]


---
# 🔵 Section 5 — Sets


## 📝 Task 12 — Set Operations

### Background
A **set** is an **unordered collection of unique elements**. Duplicate values are automatically removed. Sets support mathematical operations: union (`|`), intersection (`&`), difference (`-`), symmetric difference (`^`).

| Operation | Symbol | Method | Meaning |
|-----------|--------|--------|---------|
| Union | `\|` | `.union()` | All elements from both sets |
| Intersection | `&` | `.intersection()` | Only elements in **both** |
| Difference | `-` | `.difference()` | Elements in A but **not** B |
| Symmetric Difference | `^` | `.symmetric_difference()` | Elements in either but **not both** |

### 🎯 Your Task
```python
python_students = {"Alice", "Bob", "Carol", "David", "Eve"}
java_students   = {"Bob", "David", "Frank", "Grace", "Alice"}
```

1. Find students enrolled in **both** courses (intersection)
2. Find students enrolled in **at least one** course (union)
3. Find students taking **Python but NOT Java** (difference)
4. Find students taking **exactly one** course (symmetric difference)
5. Check if `{"Bob", "Alice"}` is a **subset** of `python_students`
6. Add `"Henry"` to `python_students` and remove `"Carol"` from it
7. Create a list `[1, 2, 2, 3, 3, 3, 4, 4, 4, 4]` and use a set to print only the **unique values**

> 💡 **Hint:** Use `.issubset()` or the `<=` operator for subset check.


In [31]:
python_students = {"Alice", "Bob", "Carol", "David", "Eve"}
java_students   = {"Bob", "David", "Frank", "Grace", "Alice"}
intersection = python_students & java_students
union_set = python_students | java_students
python_not_java = python_students - java_students
exactly_one = python_students ^ java_students
subset_check = {"Bob", "Alice"}.issubset(python_students)
python_students.add("Henry")
python_students.discard("Carol")
unique_nums = set([1, 2, 2, 3, 4, 4, 5])
print("Intersection:", intersection)
print("Union:", union_set)
print("Python but not Java:", python_not_java)
print("Exactly one course:", exactly_one)
print("Subset check:", subset_check)
print("Updated python_students:", python_students)
print("Unique values:", unique_nums)


Intersection: {'David', 'Alice', 'Bob'}
Union: {'David', 'Bob', 'Frank', 'Alice', 'Eve', 'Grace', 'Carol'}
Python but not Java: {'Carol', 'Eve'}
Exactly one course: {'Carol', 'Grace', 'Frank', 'Eve'}
Subset check: True
Updated python_students: {'David', 'Bob', 'Henry', 'Alice', 'Eve'}
Unique values: {1, 2, 3, 4, 5}


---
# 🔢 Section 6 — NumPy Arrays


## 📝 Task 13 — Creating & Inspecting NumPy Arrays

### Background
NumPy arrays are **fixed-type, multi-dimensional** arrays that support fast vectorised operations. Unlike Python lists, every element must be the same type. Key creation functions: `np.array()`, `np.arange()`, `np.linspace()`, `np.zeros()`, `np.ones()`, `np.eye()`, `np.random.random()`.

### 🎯 Your Task

Create each of the following arrays and print both the array and its `.shape` and `.dtype`:

| # | Function | Parameters | Expected shape |
|---|----------|------------|----------------|
| 1 | `np.arange` | 0 to 20, step 2 | `(11,)` |
| 2 | `np.linspace` | 0 to 1, 6 evenly spaced points | `(6,)` |
| 3 | `np.zeros` | 3 rows × 4 columns | `(3, 4)` |
| 4 | `np.ones` | 2 rows × 5 columns, dtype `int16` | `(2, 5)` |
| 5 | `np.eye` | 4×4 identity matrix | `(4, 4)` |
| 6 | `np.random.randint` | values 1–100, shape 3×3 | `(3, 3)` |

> 💡 **Hint:** `np.ones((2,5), dtype='int16')` creates an integer array of ones.  
> `np.random.randint(low, high, size=(r,c))` creates random integer arrays.


In [32]:
import numpy as np
arr1 = np.arange(0, 21, 2)
print(arr1, arr1.shape, arr1.dtype)
arr2 = np.linspace(0, 1, 6)
print(arr2, arr2.shape, arr2.dtype)
arr3 = np.zeros((3, 4))
print(arr3, arr3.shape, arr3.dtype)
arr4 = np.ones((2, 5), dtype=np.int16)
print(arr4, arr4.shape, arr4.dtype)
arr5 = np.eye(4)
print(arr5, arr5.shape, arr5.dtype)
arr6 = np.random.randint(1, 101, size=(3, 3))
print(arr6, arr6.shape, arr6.dtype)


[ 0  2  4  6  8 10 12 14 16 18 20] (11,) int32
[0.  0.2 0.4 0.6 0.8 1. ] (6,) float64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4) float64
[[1 1 1 1 1]
 [1 1 1 1 1]] (2, 5) int16
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4) float64
[[42 45 94]
 [33 91 19]
 [59 62 25]] (3, 3) int32


## 📝 Task 14 — Array Indexing, Slicing & Reshaping

### Background
NumPy arrays use **row, column** indexing: `A[row, col]` or `A[row][col]`.  
Slicing: `A[r1:r2, c1:c2]` extracts a sub-array.  
`.reshape(rows, cols)` changes the shape without changing the data.  
`.T` gives the transpose.

### 🎯 Your Task
```python
A = np.arange(1, 26).reshape(5, 5)
```
This creates:
```
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
```

1. Print the **element at row 2, column 3** (value: 14)
2. Print the **entire third row** (index 2): `[11 12 13 14 15]`
3. Print the **entire second column** (index 1): `[ 2  7 12 17 22]`
4. Extract the **top-left 3×3 sub-matrix**: rows 0–2, columns 0–2
5. Extract the **bottom-right 2×2 sub-matrix**: last 2 rows and last 2 cols
6. Print the **transpose** of A (shape should become `(5,5)` but rows/cols swapped)
7. Reshape A into a 1D array of 25 elements, then into a shape `(25, 1)` column vector

> 💡 **Hint:** `A[:3, :3]` extracts the top-left corner. `A[-2:, -2:]` grabs the bottom-right corner.


In [14]:
import numpy as np
arr1 = np.arange(0, 21, 2)
print(arr1, arr1.shape, arr1.dtype)
arr2 = np.linspace(0, 1, 6)
print(arr2, arr2.shape, arr2.dtype)
arr3 = np.zeros((3, 4))
print(arr3, arr3.shape, arr3.dtype)
arr4 = np.ones((2, 5), dtype=np.int16)
print(arr4, arr4.shape, arr4.dtype)
arr5 = np.eye(4)
print(arr5, arr5.shape, arr5.dtype)
arr6 = np.random.randint(1, 101, size=(3, 3))
print(arr6, arr6.shape, arr6.dtype)


Original matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]



## 📝 Task 15 — Vectorised Operations & Broadcasting

### Background
NumPy operations are applied **element-wise** to entire arrays without writing loops — this is called **vectorisation**. When arrays have compatible shapes, NumPy can **broadcast** smaller arrays across larger ones automatically.

### 🎯 Your Task

**Part A — Element-wise Operations:**
```python
a = np.array([10, 20, 30, 40, 50])
b = np.array([ 1,  2,  3,  4,  5])
```
Compute and print (without loops):
1. `a + b`, `a - b`, `a * b`, `a / b`
2. Square root of `a` (use `np.sqrt`)
3. All elements of `a` greater than 25 (Boolean mask)
4. Use the Boolean mask to extract only elements of `a` greater than 25

**Part B — Matrix Operations:**
```python
M = np.array([[1, 2], [3, 4]])
N = np.array([[5, 6], [7, 8]])
```
5. Element-wise multiplication `M * N`
6. Matrix (dot) product `M @ N` or `np.dot(M, N)`
7. Sum of all elements, sum along each row, sum along each column

> 💡 **Hint for Boolean masking:** `mask = a > 25` creates `[False False False True True]`. Then `a[mask]` extracts `[40 50]`.  
> 💡 **Hint for axis sums:** `M.sum(axis=1)` sums each row; `M.sum(axis=0)` sums each column.


In [33]:
import numpy as np
arr1 = np.arange(0, 21, 2)
print(arr1, arr1.shape, arr1.dtype)
arr2 = np.linspace(0, 1, 6)
print(arr2, arr2.shape, arr2.dtype)
arr3 = np.zeros((3, 4))
print(arr3, arr3.shape, arr3.dtype)
arr4 = np.ones((2, 5), dtype=np.int16)
print(arr4, arr4.shape, arr4.dtype)
arr5 = np.eye(4)
print(arr5, arr5.shape, arr5.dtype)
arr6 = np.random.randint(1, 101, size=(3, 3))
print(arr6, arr6.shape, arr6.dtype)


[ 0  2  4  6  8 10 12 14 16 18 20] (11,) int32
[0.  0.2 0.4 0.6 0.8 1. ] (6,) float64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4) float64
[[1 1 1 1 1]
 [1 1 1 1 1]] (2, 5) int16
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4) float64
[[45 22 87]
 [54 31 75]
 [18 41 46]] (3, 3) int32


---
# 🐼 Section 7 — Pandas DataFrames


## 📝 Task 16 — Creating & Exploring a DataFrame

### Background
A **DataFrame** is a 2D table with labelled rows (index) and columns. You can create one from a dictionary, a list of lists, a CSV file, or from scikit-learn datasets. Essential inspection methods: `.head()`, `.tail()`, `.info()`, `.describe()`, `.shape`, `.columns`, `.dtypes`, `.isnull().sum()`.

### 🎯 Your Task

**Part A — Create from a dictionary:**
```python
data = {
    "Name":    ["Ali", "Sara", "John", "Fatima", "Chris"],
    "Age":     [23, 21, 25, 22, 24],
    "Score":   [88, 92, 78, 95, 83],
    "Passed":  [True, True, True, True, True],
    "City":    ["Lahore", "Karachi", "London", "Islamabad", "New York"]
}
```
1. Create a DataFrame from this dictionary
2. Print its **shape**, **column names**, and **data types**
3. Print the **first 3 rows** and the **last 2 rows**
4. Print **summary statistics** using `.describe()`

**Part B — Load the Iris dataset:**
5. Load the Iris dataset using `load_iris()` and add the species names
6. Print **how many rows belong to each species** using `.value_counts()`
7. Print the **mean of each numerical column grouped by species**

> 💡 **Hint for Iris:** `iris_df['species'] = iris.target_names[iris.target]` maps integer targets to names.  
> 💡 **Hint for groupby:** `iris_df.groupby('species').mean(numeric_only=True)`


In [34]:
import pandas as pd
from sklearn.datasets import load_iris
data = {
    "Name":   ["Ali", "Sara", "John", "Fatima", "Chris"],
    "Age":    [23, 21, 25, 22, 24],
    "Score":  [88, 92, 78, 95, 83],
    "Passed": [True, True, True, True, True],
    "City":   ["Lahore", "Karachi", "London", "Islamabad", "New York"]
}
df = pd.DataFrame(data)
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("Dtypes:\n", df.dtypes)
print("Head:\n", df.head(3))
print("Tail:\n", df.tail(2))
print("Describe:\n", df.describe(include="all"))
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df["species"] = iris.target_names[iris.target]
print("Species counts:\n", iris_df["species"].value_counts())
print("Mean by species:\n", iris_df.groupby("species").mean(numeric_only=True))


Shape: (5, 5)
Columns: ['Name', 'Age', 'Score', 'Passed', 'City']
Dtypes:
 Name      object
Age        int64
Score      int64
Passed      bool
City      object
dtype: object
Head:
    Name  Age  Score  Passed     City
0   Ali   23     88    True   Lahore
1  Sara   21     92    True  Karachi
2  John   25     78    True   London
Tail:
      Name  Age  Score  Passed       City
3  Fatima   22     95    True  Islamabad
4   Chris   24     83    True   New York
Describe:
        Name        Age     Score Passed    City
count     5   5.000000   5.00000      5       5
unique    5        NaN       NaN      1       5
top     Ali        NaN       NaN   True  Lahore
freq      1        NaN       NaN      5       1
mean    NaN  23.000000  87.20000    NaN     NaN
std     NaN   1.581139   6.83374    NaN     NaN
min     NaN  21.000000  78.00000    NaN     NaN
25%     NaN  22.000000  83.00000    NaN     NaN
50%     NaN  23.000000  88.00000    NaN     NaN
75%     NaN  24.000000  92.00000    NaN     NaN
ma

## 📝 Task 17 — Selecting, Filtering & Adding Columns

### Background
- **Select columns:** `df['col']` (Series) or `df[['col1','col2']]` (DataFrame)
- **Select rows by position:** `df.iloc[start:stop]`
- **Select rows by label/condition:** `df.loc[condition]`
- **Add a column:** `df['new_col'] = expression`
- **Multiple conditions:** Use `&` (AND) or `|` (OR) — wrap each condition in `()`

### 🎯 Your Task
Use the **Iris DataFrame** from Task 16.

1. Select and print only the `sepal length (cm)` and `petal length (cm)` columns (first 5 rows)
2. Select rows **50 through 54** using `.iloc`
3. Filter rows where `species == 'versicolor'` and print how many there are
4. Filter rows where `petal length (cm) > 5.0` **AND** `species == 'virginica'`
5. Add a new column `"petal_area"` = `petal length (cm)` × `petal width (cm)` and print the first 5 rows
6. Sort the DataFrame by `petal_area` in **descending** order and print the top 5 rows

> 💡 **Hint:** `df[(df['col1'] > val) & (df['col2'] == 'label')]` — always wrap each condition in `()`.  
> 💡 **Hint:** `df.sort_values('petal_area', ascending=False).head(5)`


In [35]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df["species"] = iris.target_names[iris.target]
print("Sepal and petal length columns (head 5):\n", iris_df[["sepal length (cm)", "petal length (cm)"]].head(5))
print("Rows 50 through 54:\n", iris_df.iloc[50:55])
versicolor = iris_df[iris_df["species"] == "versicolor"]
print("Versicolor count:", len(versicolor))
virginica_filtered = iris_df[(iris_df["petal length (cm)"] > 5.0) & (iris_df["species"] == "virginica") ]
print("Virginica with petal length > 5.0:\n", virginica_filtered)
iris_df["petal_area"] = iris_df["petal length (cm)"] * iris_df["petal width (cm)"]
print("Iris first 5 rows with petal_area:\n", iris_df.head(5))
print("Top 5 by petal_area:\n", iris_df.sort_values("petal_area", ascending=False).head(5))


Sepal and petal length columns (head 5):
    sepal length (cm)  petal length (cm)
0                5.1                1.4
1                4.9                1.4
2                4.7                1.3
3                4.6                1.5
4                5.0                1.4
Rows 50 through 54:
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

       species  
50  versicolor  
51  versicolor  
52  versicolor  
53  versicolor  
54  versicolor  
Versicolor count: 50
Virginica with petal length > 5.0:
      sepal length (cm)  sepal width (cm)  petal length (c

## 📝 Task 18 — Capstone: Combined Data Structures Challenge

### Background
Real data science tasks require combining **all** the data structures you have learned. This final task tests your ability to choose the right structure for each job.

### 🎯 Your Task
You are given student records as a **list of dictionaries**:

```python
students = [
    {"name": "Alice",   "scores": [85, 90, 78], "city": "Lahore"},
    {"name": "Bob",     "scores": [60, 55, 70], "city": "Karachi"},
    {"name": "Carol",   "scores": [92, 88, 95], "city": "Islamabad"},
    {"name": "David",   "scores": [70, 65, 80], "city": "Lahore"},
    {"name": "Eve",     "scores": [50, 45, 55], "city": "Karachi"},
    {"name": "Frank",   "scores": [88, 92, 84], "city": "Islamabad"},
    {"name": "Grace",   "scores": [75, 80, 78], "city": "Lahore"},
]
```

Complete each of the following:

1. **Average score:** Add a key `"average"` to each student dict containing the average of their `scores` (round to 2 decimal places). Print all names and averages.

2. **Grade assignment:** Using a dictionary comprehension, create a dict `{name: grade}` where grade is:
   - `"A"` if average ≥ 85
   - `"B"` if average ≥ 70
   - `"C"` if average ≥ 55
   - `"F"` otherwise

3. **Top students:** Use a list comprehension to create a list of **names** of students with average ≥ 80.

4. **Unique cities:** Use a **set** to find all unique cities, then print them.

5. **NumPy statistics:** Convert all scores into a **2D NumPy array** (shape `7×3`). Compute and print:
   - Overall mean, min, max
   - Mean score per student (axis=1)
   - Mean score per test/column (axis=0)

6. **Pandas summary:** Create a **DataFrame** with columns `Name`, `Average`, `Grade`, `City`. Print it, then print the **average score per city** using `.groupby()`.

> 💡 **Hints:**
> - `sum(scores) / len(scores)` or `np.mean(scores)` for averages
> - `np.array([s["scores"] for s in students])` to build the 2D array
> - For the DataFrame, build a list of dicts or use parallel lists


In [36]:
import numpy as np
arr1 = np.arange(0, 21, 2)
print(arr1, arr1.shape, arr1.dtype)
arr2 = np.linspace(0, 1, 6)
print(arr2, arr2.shape, arr2.dtype)
arr3 = np.zeros((3, 4))
print(arr3, arr3.shape, arr3.dtype)
arr4 = np.ones((2, 5), dtype=np.int16)
print(arr4, arr4.shape, arr4.dtype)
arr5 = np.eye(4)
print(arr5, arr5.shape, arr5.dtype)
arr6 = np.random.randint(1, 101, size=(3, 3))
print(arr6, arr6.shape, arr6.dtype)


[ 0  2  4  6  8 10 12 14 16 18 20] (11,) int32
[0.  0.2 0.4 0.6 0.8 1. ] (6,) float64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4) float64
[[1 1 1 1 1]
 [1 1 1 1 1]] (2, 5) int16
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4) float64
[[32 58 18]
 [68 30  8]
 [40 20 49]] (3, 3) int32


---
## 🤔 Reflection Questions

Answer the following as comments in the cell below:

1. What is the key difference between a **list** and a **tuple**? When would you prefer a tuple?
2. What is the key difference between a **list** and a **set**? Give one real-world use case for each.
3. Why can't a **list** be used as a dictionary key, but a **tuple** can?
4. In Task 15, what is the advantage of NumPy **vectorisation** over using a Python `for` loop?
5. In Task 17, why do we use `&` instead of `and` when filtering a Pandas DataFrame?
6. Looking at the Capstone (Task 18), which data structure did you find most useful? Why?


In [19]:
# Q1:
# A list is ordered and mutable; a tuple is ordered and immutable. Use a tuple when the data should not change, such as fixed coordinates or record fields.

# Q2:
# A list allows duplicates and preserves order; a set stores unique elements and is unordered. Use a list for ordered collections like playlists, and a set for unique membership checks like student IDs.

# Q3:
# Lists are mutable and therefore unhashable, so they cannot be dictionary keys. Tuples are immutable and hashable, so they can be used as keys.

# Q4:
# Vectorisation lets NumPy perform operations on whole arrays at once in native code, which is much faster and more concise than Python loops.

# Q5:
# In pandas, & is used for element-wise logical comparisons on Series, while and is not supported for array-like objects.

# Q6:
# I found dictionaries and DataFrames most useful because they organize structured data cleanly and make aggregation/filtering easy.
